### ISSUE TITLE
 memory allocation failed, allocating 1024 bytes

### ISSUE THREAD

**Issue by robmarkcole** [adafruit/Adafruit_CircuitPython_DS18X20#7]
Adafruit CircuitPython 3.0.3 on 2018-10-10; Adafruit Metro M0 Express with samd21g18
I get:

```
Traceback (most recent call last):
  File "code.py", line 7, in <module>
  File "adafruit_onewire/bus.py", line 134, in scan
MemoryError: memory allocation failed, allocating 1024 bytes
```

Update: same error on Adafruit CircuitPython 3.0.3 on 2018-10-10; Adafruit Trinket M0 with samd21e18

**Comment by caternuson** [comment]
Check your hardware setup. There's no limit check on the scan, so if something weird is happening with the bus that appears to keep returning rom codes, then it will loop forever until it runs out of memory:
https://github.com/adafruit/Adafruit_CircuitPython_OneWire/blob/master/adafruit_onewire/bus.py#L134

**Comment by caternuson** [comment]
Related:
https://github.com/adafruit/Adafruit_CircuitPython_OneWire/issues/7

**Comment by caternuson** [comment]
We updated the OneWire library to limit the amount of devices it will add to the list when scanning. This should prevent the memory allocation error, but you will still get an exception thrown if something is wrong with your bus causing the scan to not go nicely. If you actually have more than the max devices, you can set the number and scan again.

Try the latest library when it goes live.

Closing for now. Re-open if needed.
